version: 2
go: &go
  environment:
    GO111MODULE: "on"
  docker:
    - image: circleci/golang:1.12
  working_directory: /go/src/github.com/moshloop/ansible-vault-run
jobs:
  release:
    <<: *go
    steps:
      - checkout
      - setup_remote_docker
      - run: go mod download
      - run: ./release.sh
workflows:
  version: 2
  build:
    jobs:
      - release:
          context: Github
